-- 037_create_master_user_and_migrate_to_multitenancy.sql
-- 멀티테넌시 구조로 전환: master_user 테이블 생성 및 기존 데이터를 휴먼로지텍(human) 테이블로 마이그레이션

-- 1. master_user 테이블 생성 (모든 기업이 공유하는 테이블)
CREATE TABLE IF NOT EXISTS drivermgm.master_user (
  id SERIAL PRIMARY KEY,
  company_name VARCHAR(255) NOT NULL UNIQUE,
  company_code VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. RLS 활성화
ALTER TABLE drivermgm.master_user ENABLE ROW LEVEL SECURITY;

-- 3. 기본 회사 "휴먼로지텍" 등록
INSERT INTO drivermgm.master_user (company_name, company_code)
VALUES ('휴먼로지텍', 'human')
ON CONFLICT (company_code) DO NOTHING;

-- 4. 기존 테이블들을 _human suffix로 복사
-- vehicles 테이블 복사
CREATE TABLE IF NOT EXISTS drivermgm.vehicles_human AS 
SELECT * FROM drivermgm.vehicles;

-- vehicle_users 테이블 복사
CREATE TABLE IF NOT EXISTS drivermgm.vehicle_users_human AS 
SELECT * FROM drivermgm.vehicle_users;

-- vehicle_field_history 테이블 복사
CREATE TABLE IF NOT EXISTS drivermgm.vehicle_field_history_human AS 
SELECT * FROM drivermgm.vehicle_field_history;

-- inspection_history 테이블 복사
CREATE TABLE IF NOT EXISTS drivermgm.inspection_history_human AS 
SELECT * FROM drivermgm.inspection_history;

-- refueling_history 테이블 복사 (존재하는 경우)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables 
             WHERE table_schema = 'drivermgm' 
             AND table_name = 'refueling_history') THEN
    CREATE TABLE IF NOT EXISTS drivermgm.refueling_history_human AS 
    SELECT * FROM drivermgm.refueling_history;
  END IF;
END $$;

-- maintenance_records 테이블 복사 (존재하는 경우)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables 
             WHERE table_schema = 'drivermgm' 
             AND table_name = 'maintenance_records') THEN
    CREATE TABLE IF NOT EXISTS drivermgm.maintenance_records_human AS 
    SELECT * FROM drivermgm.maintenance_records;
  END IF;
END $$;

-- 5. 복사된 테이블들에 Primary Key와 제약조건 추가
-- vehicles_human
ALTER TABLE drivermgm.vehicles_human ADD PRIMARY KEY (id);
ALTER TABLE drivermgm.vehicles_human ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE drivermgm.vehicles_human ENABLE ROW LEVEL SECURITY;

-- vehicle_users_human
ALTER TABLE drivermgm.vehicle_users_human ADD PRIMARY KEY (id);
ALTER TABLE drivermgm.vehicle_users_human ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE drivermgm.vehicle_users_human ENABLE ROW LEVEL SECURITY;

-- vehicle_field_history_human
ALTER TABLE drivermgm.vehicle_field_history_human ADD PRIMARY KEY (id);
ALTER TABLE drivermgm.vehicle_field_history_human ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE drivermgm.vehicle_field_history_human ENABLE ROW LEVEL SECURITY;

-- inspection_history_human
ALTER TABLE drivermgm.inspection_history_human ADD PRIMARY KEY (id);
ALTER TABLE drivermgm.inspection_history_human ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE drivermgm.inspection_history_human ENABLE ROW LEVEL SECURITY;

-- 6. public 스키마에 view 생성 (기존 view 삭제 후 재생성)
-- vehicles view
DROP VIEW IF EXISTS public.vehicles CASCADE;
CREATE OR REPLACE VIEW public.vehicles_human AS SELECT * FROM drivermgm.vehicles_human;

-- vehicle_users view
DROP VIEW IF EXISTS public.vehicle_users CASCADE;
CREATE OR REPLACE VIEW public.vehicle_users_human AS SELECT * FROM drivermgm.vehicle_users_human;

-- vehicle_field_history view
DROP VIEW IF EXISTS public.vehicle_field_history CASCADE;
CREATE OR REPLACE VIEW public.vehicle_field_history_human AS SELECT * FROM drivermgm.vehicle_field_history_human;

-- inspection_history view
DROP VIEW IF EXISTS public.inspection_history CASCADE;
CREATE OR REPLACE VIEW public.inspection_history_human AS SELECT * FROM drivermgm.inspection_history_human;

-- 7. master_user 테이블에 대한 public view 생성
CREATE OR REPLACE VIEW public.master_user AS SELECT * FROM drivermgm.master_user;

-- 8. Instead-of 트리거 함수 생성 (vehicles_human)
CREATE OR REPLACE FUNCTION public.vehicles_human_insert()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO drivermgm.vehicles_human VALUES (NEW.*);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.vehicles_human_update()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE drivermgm.vehicles_human SET
    vehicle_number = NEW.vehicle_number,
    vehicle_type = NEW.vehicle_type,
    purchase_date = NEW.purchase_date,
    driver_name = NEW.driver_name,
    current_mileage = NEW.current_mileage,
    next_inspection_date = NEW.next_inspection_date,
    insurance_expiry = NEW.insurance_expiry,
    oil_change_mileage = NEW.oil_change_mileage,
    tire_change_mileage = NEW.tire_change_mileage,
    notes = NEW.notes,
    updated_at = NEW.updated_at
  WHERE id = OLD.id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.vehicles_human_delete()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM drivermgm.vehicles_human WHERE id = OLD.id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- 트리거 생성
CREATE TRIGGER vehicles_human_insert_trigger
  INSTEAD OF INSERT ON public.vehicles_human
  FOR EACH ROW EXECUTE FUNCTION public.vehicles_human_insert();

CREATE TRIGGER vehicles_human_update_trigger
  INSTEAD OF UPDATE ON public.vehicles_human
  FOR EACH ROW EXECUTE FUNCTION public.vehicles_human_update();

CREATE TRIGGER vehicles_human_delete_trigger
  INSTEAD OF DELETE ON public.vehicles_human
  FOR EACH ROW EXECUTE FUNCTION public.vehicles_human_delete();

-- 완료 메시지
DO $$
BEGIN
  RAISE NOTICE 'Multi-tenancy migration completed successfully!';
  RAISE NOTICE '기본 회사 "휴먼로지텍" (코드: human) 등록 완료';
  RAISE NOTICE '기존 데이터가 _human 테이블로 마이그레이션되었습니다';
END $$;
